# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a6c4eeb5059e504df8acdfa43378fba163725fbfdb63c8b5f8d5e00e93e40c734e54bd06e1888ed81999918d262f581e0b65de25dd0380a4a270f837ec299e11

test:
  secret_key_base: 3a5863a8f68840b22780fb05c7fe1199645c96c4ad3f5eaeab8fe995fd088b035bfca1377716f9517a65e091fd9d7e15a34d46c79bbbf727b7a4ef4bbdc74b8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
